apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech
  labels:
    app: abc-tech
spec: 
  replicas: 1
  selector:
    matchlabels:
       app: abc-tech   
  template:
    metadata:
      labels:
        app: abc-tech
    spec:
      containers:
      - name: abc-tech
        image: renato71/abc_tech:latest
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: abc-tech-service
spec:
  selector:
    app: abc-tech
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer           
