apiVersion: v1
kind: Deployment
metadata:
  name: abctech
  labels:
    app: abctech
spec: 
  replicas: 1
  selector:
    matchlabels:
       app: abctech   
  template:
    metadata:
      labels:
        app: abctech
    spec:
      containers:
        name: abc_tech
        image: renato71/abc_tech:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: abc-tech-service
spec:
  selector:
    app: abctech
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer           
