apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deploy
spec: 
  selector:
    matchLabels:
      app: abc_deploy
  replicas: 1      
  template:
    metadata:
      labels:
        app: abc_deploy
    spec:
      containers:
      - name: abctech
        image: renato71/abc_tech:53
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: abc-tech
spec:
  type: NodePort 
  selector:
    app: abc_deploy
   
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30986
            
