apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deploy
spec: 
  selector:
  replicas: 1      
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: abctech
        image: renato71/abc_tech:latest
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: abc-tech
spec:
  selector:
    app: abc_deploy
  type: LoadBalancer   
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 8080
            
