apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deployment
spec:
  replicas: 1
  selector:
    matchlabels:
       app: renato71/abc-tech
  template:
    metadata:
      labels:
        app: renato71/abc-tech
    spec:
      containers:
      - name: abc-tecnologies
        image: renato71/abc_tech:39
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: abc-tech-deployment  
spec:
  selector:
    app: renato71/abc-tech 
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer           
