apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deploy
spec: 
  selector:
    matchlabels:
       app: abc_deploy
  replicas: 2    
  template:
    metadata:
      labels:
        app: abc_deploy
    spec:
      containers:
      - name: abc-tech-deploy
        image: renato71/abc_tech:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata: 
  name: abc-LoadBalencer-svc 
spec:
  selector:
    app: abc_deploy
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer           
