apiVersion: apps/v1
kind: Deployment
metadata:
  name: renato71/abc_tech
  labels:
    app: renato71/abc_tech
spec: 
  replicas: 2
  selector:
    matchlabels:
       app: renato71/abc_tech   
  template:
    metadata:
      labels:
        app: renatp71/abc_tech
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: renato71/abc_tech
        image: renato71/abc_tech:latest
        ports:
        - name: http
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: renato71/abc_tech
spec:
  selector:
    app: renato71/abc_tech
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer           
